name = "DifferenceEquations"
uuid = "e0ca9c66-1f9e-11ec-127a-1304ce62169c"
authors = ["various contributors"]
version = "0.4.10"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ChainRulesCore = "1"
CommonSolve = "0.2"
Distributions = "0.25"
PDMats = "0.11"
Parameters = "0.12"
SciMLBase = "1"
Zygote = "0.6"
julia = "1.6"
