name = "DifferenceEquations"
uuid = "e0ca9c66-1f9e-11ec-127a-1304ce62169c"
version = "0.5.3"
authors = ["various contributors"]

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Aqua = "0.8"
ChainRulesCore = "1"
ChainRulesTestUtils = "1"
CommonSolve = "0.2"
DataFrames = "1"
DelimitedFiles = "1"
DiffEqBase = "6.122"
Distributions = "0.25"
ExplicitImports = "1.9"
FiniteDiff = "2"
LinearAlgebra = "1"
PDMats = "0.11"
Plots = "1"
Random = "1"
RecursiveArrayTools = "2.25"
SciMLBase = "1.39, 2"
Test = "1"
UnPack = "1"
Zygote = "0.6"
julia = "1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Aqua", "ChainRulesTestUtils", "DataFrames", "DelimitedFiles", "ExplicitImports", "FiniteDiff", "Plots", "Random", "Test", "Zygote"]
