name = "DifferenceEquations"
uuid = "e0ca9c66-1f9e-11ec-127a-1304ce62169c"
authors = ["various contributors"]
version = "0.4.11"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"

[compat]
ChainRulesCore = "1"
CommonSolve = "0.2"
DiffEqBase = "6.82"
Distributions = "0.25"
PDMats = "0.11"
RecursiveArrayTools = "2.25"
SciMLBase = "1"
UnPack = "1"
julia = "1.6, 1.7"
CPUSummary = "=0.1.8"
